Document: vibe2sewer
Title: Debian vibe2sewer Manual
Author: <insert document author here>
Abstract: This manual describes what vibe2sewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vibe2sewer/vibe2sewer.sgml.gz

Format: postscript
Files: /usr/share/doc/vibe2sewer/vibe2sewer.ps.gz

Format: text
Files: /usr/share/doc/vibe2sewer/vibe2sewer.text.gz

Format: HTML
Index: /usr/share/doc/vibe2sewer/html/index.html
Files: /usr/share/doc/vibe2sewer/html/*.html
